// Shared site script: translations (EN / 繁 / 简), language switcher, header and menu.
// Used by index.html and capabilities.html.
const translations={
  en:{
    'nav.capabilities':'Capabilities','capMeta.title':'Capabilities — Lotus EdTech','capMeta.description':'Four connected capabilities: AI, analytics, compliance and consultancy.','cap.services':'See full services <span aria-hidden="true">→</span>',
    'meta.title':'Lotus EdTech — AI, Analytics, Compliance & Consultancy','meta.description':'Lotus EdTech helps regulated and data-intensive organisations turn complex requirements and fragmented data into deployable AI, clear analytics and defensible controls.','skip':'Skip to content','aria.primaryNav':'Primary navigation','aria.home':'Lotus EdTech home','aria.language':'Language','aria.capabilities':'Lotus EdTech capabilities','aria.record':'Solid track record','aria.academic':'Team academic background','aria.backTop':'Back to top',
    'brand.tagline':'Intelligence · Delivered','nav.services':'Services','nav.engagements':'Engagements','nav.approach':'Approach','nav.experience':'Experience','nav.about':'About us','nav.cta':'Discuss a project ↗','nav.menu':'MENU','nav.close':'CLOSE',
    'hero.eyebrow':'AI · Analytics · Compliance · Consultancy','hero.title':'Complexity, made <em>operational.</em>','hero.lead':'Lotus EdTech helps regulated and data-intensive organisations turn complex requirements and fragmented data into deployable systems, defensible controls and better decisions.','hero.cta':'Discuss a project <span aria-hidden="true">↗</span>','hero.explore':'Explore our services <span aria-hidden="true">↓</span>','hero.proof':'Proven across SFC applications · AI agents · Data analytics',
    'brief.title':'Capability brief','brief.status':'Delivery-focused','brief.ai':'AI','brief.aiDesc':'From viable use case to governed workflow.','brief.analytics':'Analytics','brief.analyticsDesc':'From scattered data to decision-ready insight.','brief.compliance':'Compliance','brief.complianceDesc':'From obligation to evidence and control.','brief.consultancy':'Consultancy','brief.consultancyDesc':'From ambiguity to a practical delivery plan.',
    'record.sfcLabel':'Solid track record','record.sfcTitle':'SFC applications','record.sfcDesc':'Supporting complex applications and regulatory submissions.','record.dataLabel':'Proven delivery','record.dataTitle':'Data analytics','record.dataDesc':'Decision systems, quantitative analysis and reporting built for real use.','record.aiLabel':'Hands-on capability','record.aiTitle':'AI agents','record.aiDesc':'Agentic workflows and knowledge systems taken from design to deployment.',
    'services.eyebrow':'Four connected capabilities','services.title':'Advice that ends in <em>working change.</em>','services.intro':'Technology, governance and commercial judgement—connected from analysis to implementation.',
    'service.aiMeta':'Proven agent delivery','service.aiTitle':'AI & Automation','service.aiDesc':'Hands-on track record delivering AI agents and governed workflows.','service.ai1':'AI agents','service.ai2':'RAG & knowledge systems','service.ai3':'Model governance',
    'service.dataMeta':'Proven analytics','service.dataTitle':'Data & Analytics','service.dataDesc':'Track record turning complex data into live decision tools.','service.data1':'Data strategy','service.data2':'Dashboards','service.data3':'Risk analytics',
    'service.complianceMeta':'Make controls real','service.complianceTitle':'Compliance & Governance','service.complianceDesc':'Turn obligations into evidence, ownership and control.','service.compliance1':'Readiness reviews','service.compliance2':'Control design','service.compliance3':'AI & data governance',
    'service.consultMeta':'Solid SFC track record','service.consultTitle':'Strategic Consultancy','service.consultDesc':'Demonstrated experience supporting complex SFC applications.','service.consult1':'SFC applications','service.consult2':'Algorithmic trading','service.consult3':'Virtual assets','service.consult4':'Delivery roadmaps',
    'engage.eyebrow':'Start where the pressure is','engage.title':'Focused projects. Tangible outputs.','engage.intro':'A defined diagnostic, delivery sprint or embedded mandate.','engage.item1':'AI and data opportunity diagnostic','engage.tag1':'Prioritise','engage.item2':'Compliance readiness review','engage.tag2':'De-risk','engage.item3':'Control and reporting design','engage.tag3':'Evidence','engage.item4':'Prototype and implementation sprint','engage.tag4':'Build','engage.item5':'Strategy and operating-model mandate','engage.tag5':'Transform',
    'approach.eyebrow':'How we work','approach.title':'Rigorous by design. Practical in delivery.','approach.step1':'01 / FRAME','approach.item1':'Define the decision','approach.desc1':'Outcome, context and success measures.','approach.step2':'02 / BUILD','approach.item2':'Design the solution','approach.desc2':'Analysis, process and technology.','approach.step3':'03 / EMBED','approach.item3':'Make it sustainable','approach.desc3':'Ownership, controls and measures.',
    'proof.kicker':'Operating proof · Flagship platform','proof.desc':'Our AI-powered platform turns complex Hong Kong retirement-fund data into clear comparisons and plain-language insight.','proof.link':'Visit mpfgo.hk <span aria-hidden="true">↗</span>','proof.chart1':'Fund intelligence','proof.chart2':'Signal / trend','proof.point1Label':'01 / DATA','proof.point1':'Structured inputs','proof.point2Label':'02 / INSIGHT','proof.point2':'Clear signals','proof.point3Label':'03 / DELIVERY','proof.point3':'Live product',
    'company.eyebrow':'About us','company.title':'Senior expertise across regulation, data and AI.','company.desc1':'Lotus EdTech is a Hong Kong-based specialist consultancy. We combine regulatory experience with hands-on technology delivery—turning complex requirements into practical, defensible outcomes.','company.desc2':'Our track record spans complex SFC applications, AI agents, decision-grade analytics and live financial products. Team members hold advanced degrees from UC Berkeley, Stanford and HKU.','company.berkeley':'UC BERKELEY','company.stanford':'STANFORD','company.hku':'HKU',
    'contact.eyebrow':'Start a conversation','contact.title':'Bring us the problem between <em>business and complexity.</em>','contact.desc':'Tell us what needs to change. We will show you how we can help.','contact.location':'Hong Kong SAR','contact.address1':'22/F, Tower 2, New World Tower','contact.address2':"18 Queen's Road Central",
    'footer.company':'About us','footer.contact':'Contact','footer.operator':'Operator of MPFGo','footer.disclaimer':'Lotus EdTech provides technology, analytics and business advisory services. Engagement scope is agreed case by case; nothing on this website constitutes legal advice.'
  },
  'zh-Hant':{
    'nav.capabilities':'核心能力','capMeta.title':'核心能力 — Lotus EdTech','capMeta.description':'四項相互連結的能力：人工智能、數據分析、合規及顧問服務。','cap.services':'查看完整服務 <span aria-hidden="true">→</span>',
    'meta.title':'Lotus EdTech — 人工智能、數據分析、合規及顧問服務','meta.description':'Lotus EdTech 協助受規管及數據密集型機構，將複雜要求與零散數據轉化為可落地的人工智能、清晰分析及可驗證的管控措施。','skip':'跳至主要內容','aria.primaryNav':'主要導覽','aria.home':'Lotus EdTech 首頁','aria.language':'語言','aria.capabilities':'Lotus EdTech 服務能力','aria.record':'穩健實績','aria.academic':'團隊學術背景','aria.backTop':'返回頁首',
    'brand.tagline':'智能 · 落地','nav.services':'服務','nav.engagements':'合作項目','nav.approach':'工作方式','nav.experience':'實績','nav.about':'關於我們','nav.cta':'洽談項目 ↗','nav.menu':'選單','nav.close':'關閉',
    'hero.eyebrow':'人工智能 · 數據分析 · 合規 · 顧問服務','hero.title':'化繁為<em>行。</em>','hero.lead':'Lotus EdTech 協助受規管及數據密集型機構，將複雜要求與零散數據轉化為可落地的系統、可驗證的管控措施及更明智的決策。','hero.cta':'洽談項目 <span aria-hidden="true">↗</span>','hero.explore':'了解我們的服務 <span aria-hidden="true">↓</span>','hero.proof':'具備實績：證監會申請 · AI 智能體 · 數據分析',
    'brief.title':'能力概覽','brief.status':'著重落地','brief.ai':'人工智能','brief.aiDesc':'由可行用例到受管控的工作流程。','brief.analytics':'數據分析','brief.analyticsDesc':'由零散數據到決策洞見。','brief.compliance':'合規','brief.complianceDesc':'由監管要求到證據與管控。','brief.consultancy':'顧問服務','brief.consultancyDesc':'由模糊問題到實際執行方案。',
    'record.sfcLabel':'實績穩健','record.sfcTitle':'證監會申請','record.sfcDesc':'支援複雜牌照申請及監管文件提交。','record.dataLabel':'交付實績','record.dataTitle':'數據分析','record.dataDesc':'建立實用的決策系統、量化分析及報告。','record.aiLabel':'實戰能力','record.aiTitle':'AI 智能體','record.aiDesc':'智能體工作流程及知識系統，由設計推進至部署。',
    'services.eyebrow':'四項相互連結的能力','services.title':'顧問建議，落實為<em>實際成果。</em>','services.intro':'技術、管治與商業判斷，由分析連接至落地。',
    'service.aiMeta':'智能體交付實績','service.aiTitle':'人工智能與自動化','service.aiDesc':'具備交付 AI 智能體及受管控工作流程的實戰經驗。','service.ai1':'AI 智能體','service.ai2':'RAG 與知識系統','service.ai3':'模型管治',
    'service.dataMeta':'分析交付實績','service.dataTitle':'數據與分析','service.dataDesc':'具備將複雜數據轉化為實用決策工具的往績。','service.data1':'數據策略','service.data2':'管理儀表板','service.data3':'風險分析',
    'service.complianceMeta':'落實管控','service.complianceTitle':'合規與管治','service.complianceDesc':'將監管要求轉化為證據、責任與管控。','service.compliance1':'合規準備評估','service.compliance2':'管控設計','service.compliance3':'AI 與數據管治',
    'service.consultMeta':'證監會申請實績','service.consultTitle':'策略顧問','service.consultDesc':'具備支援複雜證監會申請的實績。','service.consult1':'證監會申請','service.consult2':'算法交易','service.consult3':'虛擬資產','service.consult4':'交付路線圖',
    'engage.eyebrow':'由最迫切問題開始','engage.title':'專注項目。明確成果。','engage.intro':'可從診斷、交付衝刺或嵌入式顧問合作開始。','engage.item1':'AI 與數據機會診斷','engage.tag1':'排序','engage.item2':'合規準備評估','engage.tag2':'降險','engage.item3':'管控與報告設計','engage.tag3':'證據','engage.item4':'原型與實施衝刺','engage.tag4':'建構','engage.item5':'策略與營運模式顧問','engage.tag5':'轉型',
    'approach.eyebrow':'工作方式','approach.title':'嚴謹設計。務實交付。','approach.step1':'01 / 界定','approach.item1':'界定決策','approach.desc1':'成果、背景及成功標準。','approach.step2':'02 / 設計','approach.item2':'設計方案','approach.desc2':'分析、流程與技術。','approach.step3':'03 / 融入','approach.item3':'建立持續能力','approach.desc3':'責任、管控與衡量標準。',
    'proof.kicker':'營運實證 · 旗艦平台','proof.desc':'我們的 AI 平台將香港退休基金的複雜數據轉化為清晰比較與淺白洞見。','proof.link':'瀏覽 mpfgo.hk <span aria-hidden="true">↗</span>','proof.chart1':'基金智能','proof.chart2':'信號 / 趨勢','proof.point1Label':'01 / 數據','proof.point1':'結構化輸入','proof.point2Label':'02 / 洞見','proof.point2':'清晰信號','proof.point3Label':'03 / 交付','proof.point3':'營運產品',
    'company.eyebrow':'關於我們','company.title':'融合法規、數據與人工智能的資深專業團隊。','company.desc1':'Lotus EdTech 是一家立足香港的專業顧問公司。我們結合法規經驗與科技交付能力，將複雜要求轉化為務實、可驗證的成果。','company.desc2':'實績涵蓋複雜證監會申請、AI 智能體、決策級數據分析及營運中的金融產品。團隊成員擁有加州大學柏克萊分校、史丹福大學及香港大學的高等學位。','company.berkeley':'加州大學柏克萊分校','company.stanford':'史丹福大學','company.hku':'香港大學',
    'contact.eyebrow':'展開對話','contact.title':'把<em>業務與複雜性之間</em>的難題交給我們。','contact.desc':'告訴我們需要改變甚麼，我們會提出可行方案。','contact.location':'香港特別行政區','contact.address1':'新世界大廈二期22樓','contact.address2':'中環皇后大道中18號',
    'footer.company':'關於我們','footer.contact':'聯絡','footer.operator':'MPFGo 營運方','footer.disclaimer':'Lotus EdTech 提供技術、數據分析及商業顧問服務。服務範圍按個別項目議定；本網站任何內容均不構成法律意見。'
  },
  'zh-Hans':{
    'nav.capabilities':'核心能力','capMeta.title':'核心能力 — Lotus EdTech','capMeta.description':'四项相互连接的能力：人工智能、数据分析、合规及咨询服务。','cap.services':'查看完整服务 <span aria-hidden="true">→</span>',
    'meta.title':'Lotus EdTech — 人工智能、数据分析、合规及咨询服务','meta.description':'Lotus EdTech 协助受监管及数据密集型机构，将复杂要求与零散数据转化为可落地的人工智能、清晰分析及可验证的管控措施。','skip':'跳至主要内容','aria.primaryNav':'主要导航','aria.home':'Lotus EdTech 首页','aria.language':'语言','aria.capabilities':'Lotus EdTech 服务能力','aria.record':'稳健实绩','aria.academic':'团队学术背景','aria.backTop':'返回页首',
    'brand.tagline':'智能 · 落地','nav.services':'服务','nav.engagements':'合作项目','nav.approach':'工作方式','nav.experience':'实绩','nav.about':'关于我们','nav.cta':'洽谈项目 ↗','nav.menu':'菜单','nav.close':'关闭',
    'hero.eyebrow':'人工智能 · 数据分析 · 合规 · 咨询服务','hero.title':'化繁为<em>行。</em>','hero.lead':'Lotus EdTech 协助受监管及数据密集型机构，将复杂要求与零散数据转化为可落地的系统、可验证的管控措施及更明智的决策。','hero.cta':'洽谈项目 <span aria-hidden="true">↗</span>','hero.explore':'了解我们的服务 <span aria-hidden="true">↓</span>','hero.proof':'具备实绩：证监会申请 · AI 智能体 · 数据分析',
    'brief.title':'能力概览','brief.status':'着重落地','brief.ai':'人工智能','brief.aiDesc':'由可行用例到受管控的工作流程。','brief.analytics':'数据分析','brief.analyticsDesc':'由零散数据到决策洞见。','brief.compliance':'合规','brief.complianceDesc':'由监管要求到证据与管控。','brief.consultancy':'咨询服务','brief.consultancyDesc':'由模糊问题到实际执行方案。',
    'record.sfcLabel':'实绩稳健','record.sfcTitle':'证监会申请','record.sfcDesc':'支持复杂牌照申请及监管文件提交。','record.dataLabel':'交付实绩','record.dataTitle':'数据分析','record.dataDesc':'建立实用的决策系统、量化分析及报告。','record.aiLabel':'实战能力','record.aiTitle':'AI 智能体','record.aiDesc':'智能体工作流程及知识系统，由设计推进至部署。',
    'services.eyebrow':'四项相互连接的能力','services.title':'咨询建议，落实为<em>实际成果。</em>','services.intro':'技术、治理与商业判断，由分析连接至落地。',
    'service.aiMeta':'智能体交付实绩','service.aiTitle':'人工智能与自动化','service.aiDesc':'具备交付 AI 智能体及受管控工作流程的实战经验。','service.ai1':'AI 智能体','service.ai2':'RAG 与知识系统','service.ai3':'模型治理',
    'service.dataMeta':'分析交付实绩','service.dataTitle':'数据与分析','service.dataDesc':'具备将复杂数据转化为实用决策工具的实绩。','service.data1':'数据策略','service.data2':'管理仪表板','service.data3':'风险分析',
    'service.complianceMeta':'落实管控','service.complianceTitle':'合规与治理','service.complianceDesc':'将监管要求转化为证据、责任与管控。','service.compliance1':'合规准备评估','service.compliance2':'管控设计','service.compliance3':'AI 与数据治理',
    'service.consultMeta':'证监会申请实绩','service.consultTitle':'战略咨询','service.consultDesc':'具备支持复杂证监会申请的实绩。','service.consult1':'证监会申请','service.consult2':'算法交易','service.consult3':'虚拟资产','service.consult4':'交付路线图',
    'engage.eyebrow':'由最迫切问题开始','engage.title':'专注项目。明确成果。','engage.intro':'可从诊断、交付冲刺或嵌入式咨询合作开始。','engage.item1':'AI 与数据机会诊断','engage.tag1':'排序','engage.item2':'合规准备评估','engage.tag2':'降险','engage.item3':'管控与报告设计','engage.tag3':'证据','engage.item4':'原型与实施冲刺','engage.tag4':'构建','engage.item5':'战略与运营模式咨询','engage.tag5':'转型',
    'approach.eyebrow':'工作方式','approach.title':'严谨设计。务实交付。','approach.step1':'01 / 界定','approach.item1':'界定决策','approach.desc1':'成果、背景及成功标准。','approach.step2':'02 / 设计','approach.item2':'设计方案','approach.desc2':'分析、流程与技术。','approach.step3':'03 / 融入','approach.item3':'建立持续能力','approach.desc3':'责任、管控与衡量标准。',
    'proof.kicker':'运营实证 · 旗舰平台','proof.desc':'我们的 AI 平台将香港退休基金的复杂数据转化为清晰比较与浅白洞见。','proof.link':'浏览 mpfgo.hk <span aria-hidden="true">↗</span>','proof.chart1':'基金智能','proof.chart2':'信号 / 趋势','proof.point1Label':'01 / 数据','proof.point1':'结构化输入','proof.point2Label':'02 / 洞见','proof.point2':'清晰信号','proof.point3Label':'03 / 交付','proof.point3':'运营产品',
    'company.eyebrow':'关于我们','company.title':'融合法规、数据与人工智能的资深专业团队。','company.desc1':'Lotus EdTech 是一家立足香港的专业咨询公司。我们结合法规经验与技术交付能力，将复杂要求转化为务实、可验证的成果。','company.desc2':'实绩涵盖复杂证监会申请、AI 智能体、决策级数据分析及运营中的金融产品。团队成员拥有加州大学伯克利分校、斯坦福大学及香港大学的高等学位。','company.berkeley':'加州大学伯克利分校','company.stanford':'斯坦福大学','company.hku':'香港大学',
    'contact.eyebrow':'展开对话','contact.title':'把<em>业务与复杂性之间</em>的难题交给我们。','contact.desc':'告诉我们需要改变什么，我们会提出可行方案。','contact.location':'香港特别行政区','contact.address1':'新世界大厦二期22楼','contact.address2':'中环皇后大道中18号',
    'footer.company':'关于我们','footer.contact':'联系','footer.operator':'MPFGo 运营方','footer.disclaimer':'Lotus EdTech 提供技术、数据分析及商业咨询服务。服务范围按个别项目议定；本网站任何内容均不构成法律意见。'
  }
};
const header=document.getElementById('header');const menuButton=document.querySelector('.menu-toggle');const navLinks=document.getElementById('nav-links');const languageButtons=document.querySelectorAll('[data-lang]');const metaDescription=document.querySelector('meta[name="description"]');let currentLanguage='en';
const textFor=key=>translations[currentLanguage]?.[key]??translations.en[key]??key;
function setLanguage(language,persist=true){
  currentLanguage=translations[language]?language:'en';document.documentElement.lang=currentLanguage;
  document.querySelectorAll('[data-i18n]').forEach(element=>{element.textContent=textFor(element.dataset.i18n)});
  document.querySelectorAll('[data-i18n-html]').forEach(element=>{element.innerHTML=textFor(element.dataset.i18nHtml)});
  document.querySelectorAll('[data-i18n-aria]').forEach(element=>{element.setAttribute('aria-label',textFor(element.dataset.i18nAria))});
  const metaKey=document.body.dataset.meta||'meta';document.title=textFor(metaKey+'.title');metaDescription.setAttribute('content',textFor(metaKey+'.description'));
  languageButtons.forEach(button=>{const active=button.dataset.lang===currentLanguage;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});
  menuButton.textContent=textFor(navLinks.classList.contains('open')?'nav.close':'nav.menu');
  if(persist){try{localStorage.setItem('lotus-language',currentLanguage)}catch(error){}const url=new URL(location.href);if(currentLanguage==='en')url.searchParams.delete('lang');else url.searchParams.set('lang',currentLanguage);history.replaceState({},'',url)}
}
const requestedLanguage=new URLSearchParams(location.search).get('lang');let savedLanguage='';try{savedLanguage=localStorage.getItem('lotus-language')||''}catch(error){}setLanguage(requestedLanguage||savedLanguage||'en',false);
languageButtons.forEach(button=>button.addEventListener('click',()=>setLanguage(button.dataset.lang)));
const updateHeader=()=>header.classList.toggle('scrolled',window.scrollY>20);updateHeader();window.addEventListener('scroll',updateHeader,{passive:true});
menuButton.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.textContent=textFor(open?'nav.close':'nav.menu')});
navLinks.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navLinks.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.textContent=textFor('nav.menu')}));
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(!reduced&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');observer.unobserve(entry.target)}})},{threshold:.12});document.querySelectorAll('.reveal:not(.in)').forEach(element=>observer.observe(element))}else{document.querySelectorAll('.reveal').forEach(element=>element.classList.add('in'))}
document.getElementById('year').textContent=new Date().getFullYear();
